# authors:
# David Hernandez Lopez, david.hernandez@uclm.es
# Ana del Campo Sanchez, ana.delcampo@usal.es

DEFAULT_GEOIDS_PATH = "Agisoft/Metashape Pro/geoids"
PARAMS_DEFINITION_FILE = "params_definition.json"
CONST_PROJECTS_STRING_SEPARATOR = ";"
CONST_NO_COMBO_SELECT = " ... "
SETTINGS_FILE = "setting.ini"
TEMPLATE_PATH = "\\templates"
GUI_LANGUAGE_TAG = "Language"
OBJECT_CLASS_PROJECT = "Project"
OBJECT_CLASS_WORKFLOW = "Workflow"
OBJECT_CLASS_PHOTO = "Photo"
OBJECT_CLASS_ROI = "ROI"
OBJECT_CLASS_CAMERA_CALIBRATION = "CameraCalibration"
OBJECT_CLASS_OPTIMIZE_ALIGNMENT = "OptimizeAlignment"
OBJECT_CLASS_SPLIT_TILE = "SplitTile"
OBJECT_CLASS_POINT_CLOUD = "PointCloud"
OBJECT_CLASS_INSTALL_REQUIREMENT = "InstallRequirement"
# OBJECT_CLASS_PROJECT = "Project"
GUI_CLASSES = [OBJECT_CLASS_PROJECT, OBJECT_CLASS_WORKFLOW, OBJECT_CLASS_PHOTO, OBJECT_CLASS_ROI,
               OBJECT_CLASS_CAMERA_CALIBRATION, OBJECT_CLASS_OPTIMIZE_ALIGNMENT, OBJECT_CLASS_SPLIT_TILE,
               OBJECT_CLASS_POINT_CLOUD, OBJECT_CLASS_INSTALL_REQUIREMENT]
GRID_LAYOUT_POSITION_BY_CLASS = {}
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_PROJECT] = [0, 0]
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_WORKFLOW] = [0, 1]
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_PHOTO] = [0, 2]
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_ROI] = [1, 0]
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_CAMERA_CALIBRATION] = [1, 1]
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_OPTIMIZE_ALIGNMENT] = [1, 2]
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_SPLIT_TILE] = [2, 0]
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_POINT_CLOUD] = [2, 1]
GRID_LAYOUT_POSITION_BY_CLASS[OBJECT_CLASS_INSTALL_REQUIREMENT] = [2, 2]
GUI_CLASSES_PROPIERTY_FIELD_DEFINITION_TAG = 'definition'
GUI_CLASSES_PROPIERTY_FIELD_TYPE_TAG = 'type'
GUI_CLASSES_PROPIERTY_FIELD_DEFAULT_TAG = 'default'
GUI_CLASSES_PROPIERTY_FIELD_DECIMALS_TAG = 'decimals'
GUI_CLASSES_PROPIERTY_FIELD_MAXIMUM_TAG = 'maximum'
GUI_CLASSES_PROPIERTY_FIELD_MINIMUM_TAG = 'minimum'
GUI_CLASSES_PROPIERTY_FIELD_SINGLE_STEP_TAG = 'singleStep'
GUI_CLASSES_PROPIERTY_FIELD_FORMATS_TAG = 'formats'
GUI_CLASSES_PROPIERTY_TYPE_STRING_TAG = 'string'
GUI_CLASSES_PROPIERTY_TYPE_BOOLEAN_TAG = 'boolean'
GUI_CLASSES_PROPIERTY_TYPE_REAL_TAG = 'real'
GUI_CLASSES_PROPIERTY_TYPE_INTEGER_TAG = 'integer'
GUI_CLASSES_PROPIERTY_TYPE_FOLDER_TAG = 'folder'
GUI_CLASSES_PROPIERTY_TYPE_FILE_OPEN_TAG = 'file open'
GUI_CLASSES_PROPIERTY_TYPE_FILE_SAVE_TAG = 'file save'
GUI_CLASSES_PROPIERTY_TYPE_VALUES_LIST_TAG = 'values'
GUI_CLASSES_PROPIERTY_TYPE_BOOLEAN_TRUE = 'True'
GUI_CLASSES_PROPIERTY_TYPE_BOOLEAN_FALSE = 'False'
GUI_CLASSES_TEXT_TAG = 'text'
PARAMETER_JSON_CONTENT = "json_content"
parameters = {}
for gui_class in GUI_CLASSES:
    parameter = {}
    parameter[PARAMETER_JSON_CONTENT] = None
    parameters[gui_class] = parameter
GUI_CLASSES_PROPIERTY_VALUE_SUFFIX = '_value'
GUI_CLASSES_PATH = "\\gui"
PROJECT_LABEL_DEFAULT = "example"
PROJECT_EPSG_DEFAULT = "25830+5782"
PROJECT_DEM_GSD_DEFAULT = 0.05
PROJECT_ORTHO_GSD_DEFAULT = 0.05
REQUIREMENTS_CONDA_ENVIRONMENT_TAG = "Env"
REQUIREMENTS_GEOIDS_PATH_TAG = "Geoid"

