# authors:
# David Hernandez Lopez, david.hernandez@uclm.es
# Ana del Campo Sanchez, ana.delcampo@usal.es

PARAMS_DEFINITION_FILE = "params_definition.json"
TEMPLATE_PATH = "\\templates"
GUI_CLASSES = ["Project", "Workflow", "Photo", "ROI", "CameraCalibration",
               "OptimizeAlignment", "SplitTile", "PointCloud", "InstallRequirement"]
GUI_CLASSES_PROPIERTY_FIELD_DEFINITION_TAG = 'definition'
GUI_CLASSES_PROPIERTY_FIELD_TYPE_TAG = 'type'
GUI_CLASSES_PROPIERTY_FIELD_DEFAULT_TAG = 'default'
GUI_CLASSES_PROPIERTY_FIELD_DECIMALS_TAG = 'decimals'
GUI_CLASSES_PROPIERTY_FIELD_MAXIMUM_TAG = 'maximum'
GUI_CLASSES_PROPIERTY_FIELD_MINIMUM_TAG = 'minimum'
GUI_CLASSES_PROPIERTY_FIELD_SINGLE_STEP_TAG = 'singleStep'
GUI_CLASSES_PROPIERTY_TYPE_STRING_TAG = 'string'
GUI_CLASSES_PROPIERTY_TYPE_BOOLEAN_TAG = 'boolean'
GUI_CLASSES_PROPIERTY_TYPE_REAL_TAG = 'real'
GUI_CLASSES_PROPIERTY_TYPE_INTEGER_TAG = 'integer'
GUI_CLASSES_PROPIERTY_TYPE_FOLDER_TAG = 'folder'
GUI_CLASSES_PROPIERTY_TYPE_FILE_OPEN_TAG = 'file open'
GUI_CLASSES_PROPIERTY_TYPE_FILE_SAVE_TAG = 'file save'
GUI_CLASSES_PROPIERTY_TYPE_VALUES_LIST_TAG = 'values'
GUI_CLASSES_PROPIERTY_TYPE_BOOLEAN_TRUE = 'True'
GUI_CLASSES_PROPIERTY_TYPE_BOOLEAN_FALSE = 'False'

GUI_CLASSES_PATH = "\\gui"
PROJECT_LABEL_DEFAULT = "example"
PROJECT_EPSG_DEFAULT = "25830+5782"
PROJECT_DEM_GSD_DEFAULT = 0.05
PROJECT_ORTHO_GSD_DEFAULT = 0.05

